// A cybersecurity operations team is reviewing encrypted communication logs generated by internal services within a distributed system.
// Each log is represented as a string containing only three specific signal markers:
// a indicates an authentication event
// b indicates an authorization event
// c indicates a confirmation event
// For a communication segment to be considered secure and valid, it must include at least one occurrence of all three signal markers.
// You are given a string s that represents a continuous stream of these communication signals over time.
// Your task is to determine how many contiguous communication windows (substrings) exist such that each window contains at least one a, one b, and one c.
// Return the total count of such valid communication windows.
// This metric helps the team assess how frequently complete security handshakes occur within the system.
// Example 1
// Input:
// abcabc
// Output:
// 10
// Explanation:
// The valid communication windows are:
// abc
// abca
// abcab
// abcabc
// bca
// bcab
// bcabc
// cab
// cabc
// abc
// Each of these substrings contains all three required signal markers.
// Example 2
// Input:
// aaacb
// Output:
// 3
// Explanation:
// The valid communication windows are:
// aaacb
// aacb
// acb
// Input Format:
// A single string s representing the communication signal stream
// Output Format:
// Return a single integer, the number of valid communication windows
import java.util.*;
public class Count_substring_having_a_b_c {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String s = sc.next();
        System.out.println(countSecureWindows(s));
    }   
    public static long countSecureWindows(String s) {
        int n = s.length();
        int[] freq = new int[3];
        int left = 0;
        long count = 0;
        for (int right = 0; right < n; right++) {
            freq[s.charAt(right) - 'a']++;
            while (freq[0] > 0 && freq[1] > 0 && freq[2] > 0) {
                count += (n - right);
                freq[s.charAt(left) - 'a']--;
                left++;
            }
        }
        return count;
    }
}
